<?php
require_once 'config.php';

date_default_timezone_set(TIME_ZONE);
define('ACTION_ADD', 'add');
define('ACTION_ADD_ACTIVITY','add_activity');
define('ACTION_ACTIVITY_USER_LIST','activity_user_list');
define('ACTION_BACKUP', 'backup');
define('ACTION_CLEAN', 'clean');
define('ACTION_CHECK', 'check');
define('ACTION_CLOSEBY', 'closeby');
define('ACTION_DEL', 'remove');
define('ACTION_FIND', 'search');
define('ACTION_FORGOT_PASSWORD', 'forgot_password');
define('ACTION_VIEW_USER', 'view_user');
define('ACTION_FIND_LATEST_MEAL', 'find_latest_meal');
define('ACTION_FIND_FIND_LOG','find_log');
define('ACTION_LOGIN', 'login');
define('ACTION_LOGOUT', 'logout');
define('ACTION_MASSAGE_LIST', 'massage_list');
define('ACTION_MONTHLY_READ', 'monthly_read');
define('ACTION_UPDATE_PASSWORD', 'update_password');
define('ACTION_MOD', 'update');
define('ACTION_MOD_IMAGE', 'update_image');
define('ACTION_READ_OTHER', 'read_other');
define('ACTION_PASSWD', 'passwd');
define('ACTION_POPULATE', 'populate');
define('ACTION_READ', 'read');
define('ACTION_READ_ACTIVITY', 'read_act');
define('ACTION_READ_MEAL','read_meal');
define('ACTION_READ_VITAL', 'read_vital');
define('ACTION_READ_ADULT', 'read_adult');
define('ACTION_READ_INSTITUTE', 'read_institute');
define('ACTION_READ_OWNER_LOGS', 'read_owner_logs');
define('ACTION_READ_MASSAGE', 'read_massage');
define('ACTION_REFUND', 'refund');
define('ACTION_RESTORE', 'restore');
define('ACTION_RESET_PASS', 'reset_password');
define('ACTION_READ_MEDICINE', 'read_medi');
define('ACTION_READ_REPORT', 'read_report');
define('ACTION_PROGRESS_ADD', 'progress_add');
define('ACTION_PROGRESS_MOD', 'progress_update');
define('ACTION_PROGRESS_DEL', 'progress_remove');
define('ACTION_BLOOD_PRESSURE', 'blood_pressure');
define('ACTION_PULSE_RATE', 'pulse_rate');
define('ACTION_SUGAR_LEVEL', 'sugar_level');
define('ACTION_TEMPERATURE', 'temperature');
define('ACTION_BLOOD_PRESSURE_ADD', 'blood_pressure_add');
define('ACTION_PULSE_RATE_ADD', 'pulse_rate_add');
define('ACTION_SUGAR_LEVEL_ADD', 'sugar_level_add');
define('ACTION_TEMPERATURE_ADD', 'temperature_add');
define('ACTION_UPDATE', 'update_comment');
define('AUDIT_LOG_FILE_EXT', 'log');
define('AUDIT_LOG_FILE_PREFIX', '');
define('AUDIT_LOG_FILE_SUFFIX', '_audit');
define('ERR_API', "API Error");
define('ERR_AUTHENTICATION', "Unauthorized access attempt.");
define('ERR_ACTION_NOT_DEFINED', "Action is not defined");
define('ERR_ACTIVITY_ID', "Invalid activity");
define('ERR_ACTIVITY_ACCESS', "Unauthorized activity access attempt.");
define('ERR_ATTEMPT_URL', "cannot attempt this url");
define('ERR_CURRENT_PASS_NA', "The current password is not given");
define('ERR_DB_BACKUP', "DB backup failed");
define('ERR_DB_CONNECT', "Cannot connect to DB");
define('ERR_DB_DELETE', "Data deletion failed");
define('ERR_DB_DELETE_NO_CONDITION', "No condition given to remove data");
define('ERR_DB_INCORRECT_ROW_COUNT', "Unexpected number of rows");
define('ERR_DB_INSERT', "Cannot insert data to DB");
define('ERR_DB_INSERT_DUPLICATE', "Duplicate data");
define('ERR_INSERT_MEDICINE',"please insert correct medicine");
define('ERR_DB_READ', "Cannot read data from DB");
define('ERR_DB_RESTORE', "DB restore failed");
define('ERR_DB_UNKNOWN', "Unknown DB Error");
define('ERR_DB_UPDATE', "Cannot update DB");
define('ERR_DB_UPDATE_NO_DATA', "No data given to update");
define('ERR_DB_UPDATE_NO_ID', "Cannot update due to missing ID");
define('ERR_MISSING_ACTIVITY_ID', "Missing activity id");        
define('ERR_EXISTENCE', "file already exists.");
define('ERR_INVENTORY', "invalid inventory");
define('ERR_SUCCESS', "File Uploaded Successfully.");
define('ERR_SUCCESS_ACTIVITY', "Activity Done Successfully.");
define('ERR_INSERTION_MEDICINE', "desired medicine is can't find");
define('ERR_FILE_NOT_EXISTS', "The file does not exists");
define('ERR_ID_MISSING', "Missing record ID");
define('ERR_MATCH_USER', "No Matching user to activity");
define('ERR_MISSING_PARTNER_ID', "Missing massage ID");
define('ERR_LOGIN', "Error Login. Please login again and try.");
define('ERR_MULTY_MATCH', "Matching Multiple Items");
define('ERR_NO_MATCH', "No Matching Items");
define('ERR_NON_SINGLE_RECORD', "This operation permits exatly with one record");
define('ERR_NEW_PASS_NA', "The new password is not given");
define('ERR_NEW_PASS_NOT_MATCH', "The new password and verification are not matching");
define('ERR_NON_PERMITTED_USERNAME', "Not permitted username");
define('ERR_PARA_NOT_DEFINED', "One or more parameters are not defined");
define('ERR_PERMISSION_DENIED', "Permission denied");
define('ERR_UNKNOWN', "Unknown error");
define('ERR_UNKNOWN_ACTION', "Unknown action");
define('ERR_UNKNOWN_STATUS', "Unknown status");
define('ERR_UNKNOWN_TYPE', "Unknown type");
define('ERR_UNAVAILABLE_USERS',"unavailable users");       
define('ERR_INPUT_FEILD', "input feilds are incorrect or invalid user");
define('ERR_SESSION',  "session id is can't identify");
define('FIELD_ABOUT', 'about');
define('FIELD_ABOUT_TYPE', 'about_type');
define('FIELD_ACCESS', 'access');
define('FIELD_ACTION', 'action');
define('FIELD_ACTIVITY','activity');
define('FIELD_PARA', 'para');
define('FIELD_ASSIGNEE', 'assignee');
define('FIELD_ASSIGNEE_TYPE', 'assignee_type');
define('FIELD_CODE', 'code');
define('FIELD_COMMENT', 'comment');
define('FIELD_CREATED_TS', 'created_ts');
define('FIELD_CUST_ID', 'customer_id');
define('FIELD_DATE', 'date');
define('FIELD_DEL_DETAILS','del_details');
define('FIELD_DOSAGE', "dosage");
define('FIELD_DOSAGE_UNIT', "dosage_unit");
define('FIELD_DURATION', "duration");
define('FIELD_DURATION_UNIT', "duration_unit");
define('FIELD_EMAIL', 'email');
define('FIELD_END', 'end');
define('FIELD_END_DATE', 'end_date');
define('FIELD_END_LOC', 'end_loc');
define('FIELD_ID', 'id');
define('FIELD_ID_FROM', 'id_from');
define('FIELD_ID_TO', 'id_to');
define('FIELD_ITEM', 'item');
define('FIELD_LENGTH', 'length');
define('FIELD_LEVEL', 'level');
define('FIELD_LINE', 'line');
define('FIELD_LOGIN', 'login');
define('FIELD_MAINTENANCE_CODE', 'maintenance_code');
define('FIELD_MAINTENANCE_STATUS', 'maintenance_status');
define('FIELD_MASSAGE','massage');
define('FIELD_MOBILE', 'mobile');
define('FIELD_MED_TAKEN_BY','med_taken_by');
define('FIELD_MEDICINE', "medicine");
define('FIELD_MESSAGE', 'message');
define('FIELD_METHOD', 'method');
define('FIELD_NAME', 'name');
define('FIELD_OPENED','opened');
define('FIELD_ORDER_BY', 'order_by'); 
define('FIELD_PARENT', 'parent');
define('FIELD_PASS', 'pass'); 
define('FIELD_PASS1', 'pass1'); 
define('FIELD_PASS2', 'pass2');
define('FIELD_PROGRESS', 'progress');
define('FIELD_PATIENT_ID', 'patient_id');
define('FIELD_QUANTITY', 'quantity');
define('FIELD_READ_AS_USER', 'read_as_user');
define('FIELD_READ_ACTIVITY','read_activity');
define('FIELD_ROLE', 'role');
define('FIELD_PRESCRIBED_TO', "prescribed_to");
define('FIELD_PRESCRIBED_BY', "prescribed_by");
define('FIELD_ROUTE', "route");
define('FIELD_SCHEDULE','schedule');
define('FIELD_SESSION_ID', 'session_id');
define('FIELD_START', 'start');
define('FIELD_START_DATE', 'start_date');
define('FIELD_START_LOC', 'start_loc');
define('FIELD_STATUS', 'status');
define('FIELD_TIMESTAMP', 'timestamp');
define('FIELD_TIMING', "timing");
define('FIELD_TAKENBY', 'taken_by');
define('FIELD_TOWER_COUNT', 'tower_count');
define('FIELD_TOWER', 'tower');
define('FIELD_TYPE', 'type');
define('FIELD_TYPE_INT', 1);
define('FIELD_TYPE_STR', 2);
define('FIELD_TYPE_OTHER', 3);
define('FIELD_TYRE_NAME', 'name');
define('FIELD_UPDATED_TS', 'updated_ts');
define('FIELD_UPDATED_BY', 'updated_by');
define('FIELD_USER', 'user');
define('FIELD_USER_ID', 'user_id');
define('FIELD_VALUE', 'value');
define('FIELD_VITAL', 'vital');
define('FIND_LOG_USER', 'find_log_user');
define('JSON_DETAILS', "details");
define('JSON_STATUS', "status");
define('JSON_SUCCESS', "success");
define('JSON_TOTAL', "total");
define('JSON_NAME', "name");
define('JSON_ID', "id");
define('JSON_IMAGE', "image");
define('OK_DATA_DELETE', "Successfully removed the record");
define('OK_DATA_EMPTY_SET', "No data to display");
define('OK_DATA_INSERT', "Successfully added data");
define('OK_DATA_READ', "Successfully read data");
define('OK_DATA_UPDATE', "Successfully updated data");
define('OK_DB_BACKUP', "Successfully backed-up the database");
define('OK_DB_RESTORE', "Successfully restored database");
define('OK_LOGIN', "Successful user login");
define('OK_LOGOUT', "Successful user logout");
define('OK_USER', "User valid");
define('Plumbering', 'Plumbering');
define('Gardening', 'Gardening');
define('Medical_Supplies', 'Medical Supplies');
define('Food_Supplies', 'Food Supplies');
define('Ordinary_Supplies', 'Ordinary Supplies');
define('Reported', 'Reported');
define('Attended', 'Attended');
define('TBL_ACTIVITY_INFO', 'tbl_activity_info');
define('TBL_ACTIVITY', 'tbl_activity');
define('TBL_MEAL', 'tbl_meal');
define('TBL_MED', 'tbl_med');
define('TBL_MASSAGE','tbl_massage');
define('TBL_USER', 'tbl_user');
define('TBL_VITAL','tbl_vitals');
define('TBL_IMAGE', 'tbl_image');
define('TBL_MAINTENANCE', 'tbl_maintenance');
define('TBL_PRESCRIPTION', 'tbl_prescription');
define('TBL_INSTITUTE_INVENTORY_TX', 'tbl_institute_inventory_tx');
define('TBL_USER_INVENTORY_TX', 'tbl_user_inventory_tx');

?>